[package]
name = "cargo-tag"
version = "0.1.0"
edition = "2021"

[lib]
name = "cargo_tag"
path = "src/lib.rs"

[[bin]]
name = "cargo-tag"
path = "src/bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.27", features = ["derive"] }
semver = { version = "1.0.14", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
toml = "0.5.9"
